(************************************************************)
(* Finiteness preservation for the constructed DFA states.  *)
(************************************************************)
From Coq Require Import Lists.List.
From Coq Require Import Bool.Bool.
From Coq Require Import Logic.FunctionalExtensionality.
From PowersetProject Require Import AutomataBase.
Import ListNotations.

(*
This file proves finiteness preservation for the DFA state type
constructed by the powerset construction.

In the construction, a DFA state represents a subset of the original
NFA states. I encode such a subset as a boolean function
State -> bool, where f q = true means that q belongs to the subset.

To prove that this function type is finite, I first generate all
list-based subsets of the finite list of states using powerset. Then
I convert each list subset into a boolean membership function using
list_to_fun.  This gives a finite list of candidate DFA states.

The main coverage argument goes in the other direction. Given an
arbitrary function f : State -> bool, fun_to_list collects exactly the
states where f is true. This list is one of the subsets generated by
powerset and converting it back with list_to_fun gives the original
function f. Therefore, no function state is missed.

Finally, to build a full FiniteType record, I also define decidable
equality for function states, remove duplicates using nodup, prove
NoDup, and package everything as DState_FiniteType.
*)
Section Finiteness.

Variable State : FiniteType.

Definition DState' : Type := State -> bool.

(* powerset xs returns all list-based subsets of xs. *)
Fixpoint powerset (xs : list State) : list (list State) :=
  match xs with
  | [] => [[]]
  | x :: xs' =>
      let ps := powerset xs' in
      ps ++ map (fun ys => x :: ys) ps
  end.

(* Turn a list subset into its membership function. *)
Definition list_to_fun (xs : list State) : DState' :=
  fun s =>
    match in_dec (finite_eq_dec State) s xs with
    | left _ => true
    | right _ => false
    end.

(* Keep exactly the states on which f is true. *)
Fixpoint true_states (f : DState') (xs : list State) : list State :=
  match xs with
  | [] => []
  | x :: xs' =>
      match f x with
      | true => x :: true_states f xs'
      | false => true_states f xs'
      end
  end.

Definition fun_to_list (f : DState') : list State :=
  true_states f (finite_list State).

Definition all_powerset_states : list DState' :=
  map list_to_fun (powerset (finite_list State)).

Lemma list_to_fun_true :
  forall (xs : list State) (s : State),
    list_to_fun xs s = true <-> In s xs.
Proof.
  intros xs s.
  unfold list_to_fun.
  destruct (in_dec (finite_eq_dec State) s xs) as [Hin | Hnot].
  - split.
    + intros. exact Hin.
    + intros. reflexivity.
  - split.
    + intro H. discriminate H.
    + intro H. contradiction.
Qed.

Lemma true_states_correct :
  forall (f : DState') (xs : list State) (s : State),
    In s (true_states f xs) <-> In s xs /\ f s = true.
Proof.
  intros f xs.
  induction xs as [|x xs' IH].
  - intro s. simpl.
    split.
    + intro H. contradiction.
    + intros [H _]. contradiction.
  - intro s. simpl.
    destruct (f x) eqn:Hfx.
    + simpl.
      split.
      * intro H.
        destruct H as [H | H].
        -- subst s. split.
           ++ left. reflexivity.
           ++ exact Hfx.
        -- apply IH in H.
           destruct H as [Hs Hfs].
           split.
           ++ right. exact Hs.
           ++ exact Hfs.
      * intros [[H | H] Hfs].
        -- subst s. left. reflexivity.
        -- right. apply IH. split; assumption.
    + split.
      * intro H.
        apply IH in H.
        destruct H as [Hs Hfs].
        split.
        -- right. exact Hs.
        -- exact Hfs.
      * intros [[H | H] Hfs].
        -- subst s. rewrite Hfx in Hfs. discriminate Hfs.
        -- apply IH. split; assumption.
Qed.

Lemma fun_to_list_correct :
  forall (f : DState') (s : State),
    In s (fun_to_list f) <->
    In s (finite_list State) /\ f s = true.
Proof.
  intros f s.
  unfold fun_to_list.
  apply true_states_correct.
Qed.

(* The two representations agree: converting f to a list of true
   states and then back to a membership function gives the same f. *)
Lemma list_to_fun_fun_to_list :
  forall f : DState', list_to_fun (fun_to_list f) = f.
Proof.
  intro f.
  apply functional_extensionality.
  intro x.
  destruct (f x) eqn:Hfx.
  - apply list_to_fun_true.
    unfold fun_to_list.
    apply true_states_correct.
    split.
    + apply finite_cover.
    + exact Hfx.
  - destruct (list_to_fun (fun_to_list f) x) eqn:Hmem.
    + apply list_to_fun_true in Hmem.
      unfold fun_to_list in Hmem.
      apply true_states_correct in Hmem.
      destruct Hmem as [_ Hfalse].
      rewrite Hfx in Hfalse.
      discriminate Hfalse.
    + reflexivity.
Qed.

Lemma true_states_in_powerset :
  forall (f : DState') (xs : list State),
    In (true_states f xs) (powerset xs).
Proof.
  intros f xs.
  induction xs as [|x xs' IH].
  - simpl. left. reflexivity.
  - simpl.
    destruct (f x) eqn:Hfx.
    + apply in_app_iff. right.
      apply in_map. exact IH.
    + apply in_app_iff. left. exact IH.
Qed.

Lemma fun_to_list_in_powerset :
  forall f : DState',
    In (fun_to_list f) (powerset (finite_list State)).
Proof.
  intro f.
  unfold fun_to_list.
  apply true_states_in_powerset.
Qed.

Theorem all_powerset_states_cover :
  forall f : DState', In f all_powerset_states.
Proof.
  intro f.
  unfold all_powerset_states.
  rewrite <- (list_to_fun_fun_to_list f).
  apply in_map.
  apply fun_to_list_in_powerset.
Qed.

(* The previous theorem is the important coverage property.  To build
   a full FiniteType record, we also need decidable equality and NoDup. *)

Fixpoint fun_eq_on_list
  (xs : list State) (f g : DState') : bool :=
  match xs with
  | [] => true
  | x :: xs' =>
      Bool.eqb (f x) (g x) && fun_eq_on_list xs' f g
  end.

Lemma fun_eq_on_list_true :
  forall (xs : list State) (f g : DState'),
    fun_eq_on_list xs f g = true ->
    forall x : State, In x xs -> f x = g x.
Proof.
  induction xs as [|x xs' IH].
  - simpl. intros f g _ y Hy. contradiction.
  - simpl. intros f g H y Hy.
    apply andb_true_iff in H.
    destruct H as [Hhead Htail].
    destruct Hy as [Hy | Hy].
    + subst y.
      destruct (f x), (g x); simpl in Hhead;
        try discriminate Hhead; reflexivity.
    + apply (IH f g Htail y Hy).
Qed.

Lemma fun_eq_on_list_refl :
  forall (xs : list State) (f : DState'),
    fun_eq_on_list xs f f = true.
Proof.
  induction xs as [|x xs' IH].
  - intro f. reflexivity.
  - intro f. simpl.
    destruct (f x); simpl; apply IH.
Qed.

Definition DState_eq_dec :
  forall f g : DState', {f = g} + {f <> g}.
Proof.
  intros f g.
  destruct (fun_eq_on_list (finite_list State) f g) eqn:Heq.
  - left.
    apply functional_extensionality.
    intro x.
    apply (fun_eq_on_list_true
      (finite_list State) f g Heq x).
    apply finite_cover.
  - right.
    intro Hfg.
    subst g.
    pose proof (fun_eq_on_list_refl (finite_list State) f) as Hrefl.
    rewrite Hrefl in Heq.
    discriminate Heq.
Defined.

Lemma in_nodup_implies_in :
  forall (A : Type)
         (eq_dec : forall x y : A, {x = y} + {x <> y})
         (x : A) (xs : list A),
    In x (nodup eq_dec xs) -> In x xs.
Proof.
  intros A eq_dec x xs.
  induction xs as [|a xs' IH].
  - simpl. intro H. contradiction.
  - simpl.
    destruct (in_dec eq_dec a xs') as [Hin_a | Hnot_a].
    + intro H. right. apply IH. exact H.
    + simpl. intro H.
      destruct H as [H | H].
      * left. exact H.
      * right. apply IH. exact H.
Qed.

Lemma in_nodup_if_in :
  forall (A : Type)
         (eq_dec : forall x y : A, {x = y} + {x <> y})
         (x : A) (xs : list A),
    In x xs -> In x (nodup eq_dec xs).
Proof.
  intros A eq_dec x xs.
  induction xs as [|a xs' IH].
  - simpl. intro H. contradiction.
  - simpl.
    destruct (in_dec eq_dec a xs') as [Hin_a | Hnot_a].
    + intro H.
      apply IH.
      destruct H as [H | H].
      * subst a. exact Hin_a.
      * exact H.
    + intro H.
      simpl.
      destruct H as [H | H].
      * left. exact H.
      * right. apply IH. exact H.
Qed.

Lemma NoDup_nodup_custom :
  forall (A : Type)
         (eq_dec : forall x y : A, {x = y} + {x <> y})
         (xs : list A),
    NoDup (nodup eq_dec xs).
Proof.
  intros A eq_dec xs.
  induction xs as [|a xs' IH].
  - simpl. constructor.
  - simpl.
    destruct (in_dec eq_dec a xs') as [Hin_a | Hnot_a].
    + exact IH.
    + constructor.
      * intro H.
        apply Hnot_a.
        apply (in_nodup_implies_in A eq_dec a xs').
        exact H.
      * exact IH.
Qed.

Definition all_powerset_states_nodup : list DState' :=
  nodup DState_eq_dec all_powerset_states.

Lemma all_powerset_states_nodup_cover :
  forall f : DState', In f all_powerset_states_nodup.
Proof.
  intro f.
  unfold all_powerset_states_nodup.
  apply in_nodup_if_in.
  apply all_powerset_states_cover.
Qed.

Lemma all_powerset_states_nodup_NoDup :
  NoDup all_powerset_states_nodup.
Proof.
  unfold all_powerset_states_nodup.
  apply NoDup_nodup_custom.
Qed.

(* The constructed state type itself forms a FiniteType. *)
Definition DState_FiniteType : FiniteType := {|
  finite_type := DState';
  finite_list := all_powerset_states_nodup;
  finite_cover := all_powerset_states_nodup_cover;
  finite_nodup := all_powerset_states_nodup_NoDup;
  finite_eq_dec := DState_eq_dec
|}.

Definition powerset_construction_preserves_finiteness : FiniteType :=
  DState_FiniteType.

End Finiteness.
